/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qzero_mine_recognize_NativeRecognizer */

#ifndef _Included_com_qzero_mine_recognize_NativeRecognizer
#define _Included_com_qzero_mine_recognize_NativeRecognizer
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     com_qzero_mine_recognize_NativeRecognizer
	 * Method:    loadImage
	 * Signature: (Lcom/qzero/mine/recognize/Matrix;)J
	 */
	JNIEXPORT jlong JNICALL Java_com_qzero_mine_recognize_NativeRecognizer_loadImage
	(JNIEnv*, jobject, jobject);

	JNIEXPORT jlong JNICALL Java_com_qzero_mine_recognize_NativeRecognizer_loadProfile
	(JNIEnv*, jobject, jintArray, jintArray);

	/*
	 * Class:     com_qzero_mine_recognize_NativeRecognizer
	 * Method:    releaseImage
	 * Signature: (J)V
	 */
	JNIEXPORT void JNICALL Java_com_qzero_mine_recognize_NativeRecognizer_releaseImage
	(JNIEnv*, jobject, jlong);

	/*
	 * Class:     com_qzero_mine_recognize_NativeRecognizer
	 * Method:    calculateLikelihood
	 * Signature: (J[JLcom/qzero/mine/recognize/Coordinate;Lcom/qzero/mine/recognize/Coordinate;)[D
	 */
	JNIEXPORT jintArray JNICALL Java_com_qzero_mine_recognize_NativeRecognizer_calculateLikelihood
	(JNIEnv*, jobject, jlong, jlongArray, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
